on:
  push:
    branches: [dispatch]
  # pull_request_target:
  #   types: [opened, synchronize]
  #   branches:
  #     - main
  # pull_request:
    
name: ci
jobs:
  add-license:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: dispatch workflow
        uses: actions/github-script@v5
        continue-on-error: true
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'averikitsch',
              repo: 'cloud-run-microservice-template-java',
              workflow_id: 13913302,
              ref: 'main'
            });
      - name: dispatch workflow2
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            core.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'averikitsch',
              repo: 'cloud-run-microservice-template-java',
              workflow_id: 13913302,
              ref: 'main'
            });

          # core.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
          #   owner: 'octocat',
          #   repo: 'hello-world',
          #   workflow_id: 42,
          #   ref: 'ref'
          # })

          # github.rest.issues.createComment({
          #   issue_number: context.issue.number,
          #   owner: context.repo.owner,
          #   repo: context.repo.repo,
          #   body: '👋 Thanks for reporting!'
          # })
        # run: |
        #   curl -X POST https://api.github.com/repos/marcnuri-demo/actions-remote-dispatch-b/dispatches \
        #   -H 'Accept: application/vnd.github.everest-preview+json' \
        #   -u ${{ secrets.ACCESS_TOKEN }}
      # - uses: actions/checkout@v2
      #   with:
      #     ref: ${{github.event.pull_request.head.ref}}
      #     repository: ${{github.event.pull_request.head.repo.full_name}}
      # - name: format
      #   continue-on-error: true
      #   run: |-
      #     python -m pip install -r requirements-test.txt
      #     autopep8 -i app.py
      # - uses: googleapis/code-suggester@v1 # takes the changes from git directory
      #   with:
      #     command: review
      #     pull_number: ${{ github.event.pull_request.number }}
      #     git_dir: '.'