on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - main
  pull_request:
    
name: ci
jobs:
  add-license:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: format
        continue-on-error: true
        run: |-
          python -m pip install -r requirements-test.txt
          autopep8 -i app.py
      - uses: googleapis/code-suggester@v1 # takes the changes from git directory
        with:
          command: review
          pull_number: ${{ github.event.pull_request.number }}
          git_dir: '.'